version: "1.1"
"on":
  push:
    branches:
      - feature/*
stages:
  - stage:
      - git-checkout:
          alias: repo
          description: 代码仓库克隆
          version: "1.0"
          params:
            branch: ((gittar.branch))
            depth: 1
  - stage:
      - js-build:
          alias: js-script
          description: 针对 nodejs 工程的编译打包任务
          version: "1.0"
          params:
            build_cmd:
              - npm ci
            workdir: ${repo}
  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          version: "1.0"
          params:
            dice_yml: ${repo}/dice.yml
            services:
              mercado-backend:
                cmd: cd /root/js-script && pwd && ls && npm run start
                copys:
                  - ${js-script}:/root/
                image: registry.cn-hangzhou.aliyuncs.com/terminus/terminus-herd:1.1.8-node12
  - stage:
      - dice:
          alias: deploy
          description: 用于 Erda 平台部署应用服务
          params:
            release_id_path: ${release}
